version: "3.4"
services:
  youtube-retell-bot:
    image: ghcr.io/olegshulyakov/youtube-retell-bot:latest
    container_name: youtube-retell-bot
    mem_limit: 256m
    environment:
      - TELEGRAM_BOT_TOKEN= # your_telegram_bot_token
      - LLM_PROVIDER_TYPE=openai # openai/ollama
      - OPEN_AI_API_URL= #your_open_ai_provider_api_url
      - OPEN_AI_API_TOKEN= # your_open_ai_provider_api_token
      - OPEN_AI_MODEL= # your_open_ai_provider_model
      - OLLAMA_API_URL= # your_ollama_api_url
      - OLLAMA_API_TOKEN= # your_ollama_api_token
      - OLLAMA_MODEL= # your_ollama_model
    restart: unless-stopped
