spring:

  # Common
  application:
    name: youtube-briefly

  # Database
  datasource:
    url: jdbc:sqlite:./bot.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: update

  # Neural Networks
  ai:
    openai:
      base-url: ${OPENAI_BASE_URL}
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}

# Logging
logging:
  level:
    org:
      springframework:
        ai:
          DEBUG
        web:
          DEBUG
    com:
      github:
        youtubebriefly: DEBUG
