package com.github.youtubebriefly.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents a user request, likely originating from a messaging platform like Telegram.
 * This entity captures the user's ID (from the messaging platform), the text of their request,
 * and the timestamp when the request was made.
 */
@Entity
@Table(name = "UserRequest")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserRequest {

    /**
     * The unique identifier for this user request.
     * This is typically auto-generated by the database.
     */
    @Id
    private Long id;

    /**
     * The user ID from the external messaging platform (e.g., Telegram).
     * This allows us to associate the request with a specific user.
     */
    private Long userId;

    /**
     * The text content of the user's request.  This is the actual message sent by the user.
     */
    private String text;

    /**
     * The date and time when the user request was received.  This is important for tracking and analysis.
     */
    private LocalDateTime requestedAt;
}
